<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <script>
            const p = new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('aaaa');
                    // reject("def");
                }, 300);
                // 這邊用settimeout是因為讓他產生不同步
            });

            p.then((t) => {
                console.log({ t });
                //這邊回傳值可以再填入一個新的promise物件
                return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('aaaa');
                    // reject("def");
                }, 500);
            });
            })
            //這邊他回傳的是promise物件已經處理完的值，他不會回傳一個完整的promise
            .then((a) => {
                console.log({ a });
                
            })
            .catch((ex) => {
                console.log({ ex });
            });
            //catch的使用會來抓上面所有的then 因此通常放在最下面
            //用來抓例外reject用的
        </script>
    </body>
</html>
